name: Build on PR

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up ASP.NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Display current directory structure
        run: ls -R ./
      - name: pwd
        run: pwd
      - name: Restore dependencies
        run: dotnet restore ./DominandoEFCore.csproj
        


      - name: Build
        run: dotnet build ./DominandoEFCore.csproj --no-restore